# Generated by Django 3.2.22 on 2023-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
