# Generated by Django 3.2.22 on 2023-10-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231024_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default='null', max_length=200, unique=True),
        ),
    ]
