# Generated by Django 3.2.22 on 2023-10-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name']},
        ),
    ]
