# Generated by Django 3.2.22 on 2023-10-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
