# Generated by Django 3.2.3 on 2023-10-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemethod',
            old_name='Method',
            new_name='recipe_method',
        ),
    ]
