# Generated by Django 3.2.3 on 2023-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0002_rename_method_recipemethod_recipe_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='recipemethod',
            options={'verbose_name': 'Method'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='author_email',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author_name',
            field=models.CharField(default='Enter your name', max_length=150, unique=True),
        ),
    ]
