# Generated by Django 3.2 on 2023-10-26 18:18

import django.core.validators
from django.db import migrations, models
import recipe_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0003_auto_20231026_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(validators=[recipe_blog.models.field_validation, django.core.validators.MaxValueValidator(5000)], verbose_name='calories'),
        ),
    ]
