# Generated by Django 3.2 on 2023-10-26 19:00

from django.db import migrations, models
import recipe_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0004_alter_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_rating',
            field=models.FloatField(default=recipe_blog.models.Recipe.average_rating),
        ),
    ]
