# Generated by Django 3.2 on 2023-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0005_recipe_recipe_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_rating',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author_name',
            field=models.CharField(default='Enter your name', max_length=150),
        ),
    ]
