# Generated by Django 3.2 on 2023-10-27 10:43

import django.core.validators
from django.db import migrations, models
import recipe_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0006_auto_20231027_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[recipe_blog.models.field_validation, django.core.validators.MaxValueValidator(5)]),
        ),
    ]
